### ISSUE TITLE
Add option to close individual pane 

### ISSUE THREAD

**Issue by frvkl** [manogna4/obsidian-koncham-workspace#1]
This plugin is very helpful. Thank you!

It would be great if you could add the option (a right aligned icon ` x ` for each item in the list), to be able quickly close a pane directly from the list.

**Comment by manogna4** [comment]
I plan to allow a close pane function through the center-panes view, but it won't be with an `x` icon. The reason is that I don't want to take up space (however little) on the sidebar, where space is at a premium.

I will enable closing a pane through the right-click menu (on an item) instead.

I understand that the middle click is harder to implement, but possible. When I figure out how to do that, I will enable closing panes through a middle click. This is how many browsers implement it, so I hope you find it suitable.

**Comment by frvkl** [comment]
In my humble opinion, I would gladly give up a very small portion of room for the `x` icon, as it would greatly improve the speed in which we could close an item. Working with right clicking on the item and closing a note from the context-menu seems too much effort. I would more likely close the note from the close function on the pane header which already exists, than using right click on an item.

**Comment by manogna4** [comment]
noted. i suppose i can give the x a class for those who want to hide it...

**Comment by manogna4** [comment]
@frvkl I noticed you closed the issue. Have you solved it? If so, I could merge it into my plugin. I haven't had time to improve this plugin, but I mean to get back to it in a few weeks.
